person:
  # private Boolean boss;
  boss: false
  # private Date birth;
  birth: 2021/12/12
  # private Map<String, Object> maps;
  maps: {k1: v1, k2 : 12}
  # private Map<String, Dog> dogsMap;
  dogMaps: {
    k1: {
      name: dog,
      age: 12
    }
  }
  # private List<Object> lists;
  # private Object[] lists;
  lists:
    - lisi
    - zhaoliu
  # private List<Dog> dogs;
  # private Dog[] dogs;
  dogs:
    - {
        name: dog,
        age: 12
    }
  # private Dog dog
  dog:
    name: 小狗
    age: 12
server:
  port: 8080